# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [21]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [22]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([4,5,6])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[4,5,6],
          [7,8,9]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[4,5,6],
          [7,8,9],
          [10,11,12]])
a1, a2, a3

(array([4, 5, 6]),
 array([[4, 5, 6],
        [7, 8, 9]]),
 array([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((3, 3), 2, dtype('int64'), 9, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df1 = pd.DataFrame(a3)
df1

0   1   2
0   4   5   6
1   7   8   9
2  10  11  12

In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Create an array of shape (7, 2, 3) of only zeros
zero = np.zeros((7, 2, 3))
zero

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
r1 = np.arange(0, 100, 3)
r1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a4 = np.random.randint(10, size=(7, 2))
a4

array([[2, 1],
       [2, 2],
       [8, 0],
       [0, 1],
       [6, 4],
       [5, 4],
       [2, 5]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a5 = np.random.random_sample(size=(3, 5))
a5

array([[0.90907431, 0.61454963, 0.08406651, 0.90680183, 0.49966934],
       [0.00763665, 0.52862009, 0.70104938, 0.02099166, 0.06728869],
       [0.04178572, 0.18309078, 0.6863887 , 0.49397696, 0.04868649]])

In [23]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

(pseudo-)random numbers work by starting with a number (the seed), multiplying it by a large number, adding an offset, then taking modulo of that sum. The resulting number is then used as the seed to generate the next "random" number. When you set the seed (every time), it does the same thing every time, giving you the same numbers.

In [29]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand1 = np.random.randint(10,size=(3,7))
rand1

# Find the unique numbers in the array you just created
un = np.unique(rand1)
un

array([0, 1, 2, 3, 4, 5, 6, 8, 9])

In [34]:
# Find the 0'th index of the latest array you created
rand1[0]

array([6, 3, 6, 2, 5, 1, 9])

In [35]:
# Get the first 2 rows of latest array you created
rand1[0:2]

array([[6, 3, 6, 2, 5, 1, 9],
       [8, 4, 5, 3, 9, 6, 8]])

In [70]:
# Get the first 2 rows of latest array you created
rand1[:2]

array([[6, 3, 6, 2, 5, 1, 9],
       [8, 4, 5, 3, 9, 6, 8]])

In [71]:
# Get the first 2 values of the first 2 rows of the latest array
rand1[:2, :2]

array([[6, 3],
       [8, 4]])

In [72]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand2 = np.random.randint(10, size=(3, 5))
one2 = np.ones((3, 5))

In [75]:
# Add the two arrays together
res = one2 + rand2
res

array([[ 3.,  7.,  6.,  8.,  9.],
       [ 5.,  1.,  3., 10.,  8.],
       [ 6.,  8.,  9.,  4.,  1.]])

In [74]:
# Create another array of ones of shape (5, 3)
a6 = np.ones((5, 3))
a6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
# Try add the array of ones and the other most recent array together
res2 = res + a6.T
res2

array([[ 4.,  8.,  7.,  9., 10.],
       [ 6.,  2.,  4., 11.,  9.],
       [ 7.,  9., 10.,  5.,  2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [77]:
# Create another array of ones of shape (3, 5)
one3 = np.ones((3, 5))
one3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [81]:
# Subtract the new array of ones from the other most recent array
res2 - one3

array([[ 3.,  7.,  6.,  8.,  9.],
       [ 5.,  1.,  3., 10.,  8.],
       [ 6.,  8.,  9.,  4.,  1.]])

In [83]:
# Multiply the ones array with the latest array
res3 = res2 * one3
res3

array([[ 4.,  8.,  7.,  9., 10.],
       [ 6.,  2.,  4., 11.,  9.],
       [ 7.,  9., 10.,  5.,  2.]])

In [91]:
# Take the latest array to the power of 2 using '**'
res3**2

array([[ 16.,  64.,  49.,  81., 100.],
       [ 36.,   4.,  16., 121.,  81.],
       [ 49.,  81., 100.,  25.,   4.]])

In [92]:
# Do the same thing with np.square()
np.square(res3)

array([[ 16.,  64.,  49.,  81., 100.],
       [ 36.,   4.,  16., 121.,  81.],
       [ 49.,  81., 100.,  25.,   4.]])

In [93]:
# Find the mean of the latest array using np.mean()
np.mean(res3)

6.866666666666666

In [94]:
# Find the maximum of the latest array using np.max()
np.max(res3)

11.0

In [95]:
# Find the minimum of the latest array using np.min()
np.min(res3)

2.0

In [96]:
# Find the standard deviation of the latest array
np.std(res3)

2.825282680055612

In [97]:
# Find the variance of the latest array
np.var(res3)

7.982222222222221

In [98]:
# Reshape the latest array to (3, 5, 1)
rest = res3.reshape((3,5,1))
rest

array([[[ 4.],
        [ 8.],
        [ 7.],
        [ 9.],
        [10.]],

       [[ 6.],
        [ 2.],
        [ 4.],
        [11.],
        [ 9.]],

       [[ 7.],
        [ 9.],
        [10.],
        [ 5.],
        [ 2.]]])

In [99]:
# Transpose the latest array
rest.T

array([[[ 4.,  6.,  7.],
        [ 8.,  2.,  9.],
        [ 7.,  4., 10.],
        [ 9., 11.,  5.],
        [10.,  9.,  2.]]])

What does the transpose do?

Transpose permutates/rearranges the array

In [108]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(10, size=(3, 3))
arr2 = np.random.randint(10, size=(3, 2))
arr1, arr2

(array([[7, 4, 3],
        [1, 5, 5],
        [0, 8, 5]]),
 array([[2, 3],
        [3, 2],
        [9, 2]]))

In [111]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[53, 35],
       [62, 23],
       [69, 26]])

In [112]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(10, size=(4, 3))
arr4 = np.random.randint(10, size=(4, 3))
arr3, arr4

(array([[2, 3, 6],
        [3, 8, 0],
        [7, 6, 1],
        [7, 0, 8]]),
 array([[8, 1, 6],
        [9, 2, 6],
        [9, 8, 3],
        [0, 1, 0]]))

In [114]:
# Perform a dot product on the two newest arrays you created
arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [115]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3.dot(arr4.T)

array([[ 55,  60,  60,   3],
       [ 32,  43,  91,   8],
       [ 68,  81, 114,   6],
       [104, 111,  87,   0]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [117]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar1 = np.random.randint(10, size=(3, 4))
ar2 = np.random.randint(10, size=(3, 4))
ar1, ar2

(array([[8, 1, 1, 1],
        [5, 2, 8, 3],
        [0, 3, 0, 4]]),
 array([[3, 7, 7, 6],
        [2, 0, 0, 2],
        [5, 6, 5, 5]]))

In [118]:
# Compare the two arrays with '>'
ar1 > ar2

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False]])

What happens when you compare the arrays with `>`?

It returns boolean values

In [119]:
# Compare the two arrays with '>='
ar1 >= ar2

array([[ True, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [120]:
# Find which elements of the first array are greater than 7
ar1 > 7

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [126]:
# Which parts of each array are equal? (try using '==')
ar1 == ar2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [132]:
ar1

array([[1, 1, 1, 8],
       [2, 3, 5, 8],
       [0, 0, 3, 4]])

In [129]:
# Sort one of the arrays you just created in ascending order
np.sort(ar1)

array([[1, 1, 1, 8],
       [2, 3, 5, 8],
       [0, 0, 3, 4]])

In [131]:
ar1

array([[1, 1, 1, 8],
       [2, 3, 5, 8],
       [0, 0, 3, 4]])

In [134]:
ar2

array([[3, 7, 7, 6],
       [2, 0, 0, 2],
       [5, 6, 5, 5]])

In [133]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar2)

array([[0, 3, 1, 2],
       [1, 2, 0, 3],
       [0, 2, 3, 1]])

In [135]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar2)

1

In [136]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar2)

5

In [137]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar2, axis=1)

array([1, 0, 1])

In [138]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar2, axis=0)

array([1, 1, 1, 1])

In [139]:
# Create an array of normally distributed random numbers
np.random.normal(8, 2.5, 500)

array([ 7.97139138,  9.03338522,  7.64775361, 10.18040465, 11.25086287,
        4.64119059, 10.12530146,  8.98584988,  7.98826001,  4.07297004,
       11.69962194,  8.9919357 ,  3.54187234,  7.39216385,  8.81805847,
        9.26643825,  7.68098801,  8.85397701, 13.29721553, 11.86634189,
        5.62620239,  6.50775667,  7.72199   ,  3.62732641,  4.64649126,
        3.94576345,  5.13070007, 11.47400707,  5.8618987 ,  5.4323456 ,
       10.20709415,  6.87673903,  9.04659867,  6.17955188,  3.49528008,
        9.16929269,  4.12141514,  6.72376695,  6.16762216,  8.48836618,
        6.61013776,  7.68066293,  4.09860732, 13.00087022,  4.99967066,
       11.00345111,  8.37458429,  8.35226842,  8.88604896,  3.29921853,
       10.41598   ,  6.72263883, 11.02599658,  7.62191009,  7.0636961 ,
        4.77195972,  6.08622659,  9.0557844 ,  4.73021425,  3.02350113,
        5.85612779, 10.10001344, 12.45322769,  6.30646083,  4.1279283 ,
        7.14217734,  8.45963879,  9.44474284, 13.33660312,  8.56

In [121]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1, 100, 10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.